// @ts-nocheck
// This file is autogenerated by Firebase Studio. Please do not edit.

/**
 * The Firebase configuration object.
 *
 * This object is used to initialize the Firebase app.
 * It is automatically generated by Firebase Studio.
 */
export const firebaseConfig = {
  apiKey: "AIzaSyAAIAVkpcUkYBGenEWyOMRtkiYOoYu04Yg",
  authDomain: "studio-7504352207-19438.firebaseapp.com",
  projectId: "studio-7504352207-19438",
  storageBucket: "studio-7504352207-19438.firebasestorage.app",
  messagingSenderId: "828050198197",
  appId: "1:828050198197:web:46830d114fe463fdc0b8fc"
};
